### ISSUE TITLE
Usage of archived colors

### ISSUE THREAD

**Issue by kataklasm** [sainnhe/archived-colors#1]
Hello,
is there anything special I have to do to get your archived color schemes working?
I made a folder called atlantis-vim in my ~/.vim/plugged/ (for vimplug) and put atlantis.vim in it. Then I added this folder to my .vimrc VimPlug installs. When I refresh vim and apply atlantis colorscheme vim throws a bunch of errors concerning trailing characters and similar.
Thank you!

**Comment by sainnhe** [comment]
You should never use them, they are abandoned. Try other color schemes instead.

**Comment by kataklasm** [comment]
That's very disappointing as Atlantis was my favourite theme. Thank you for the quick response.

**Comment by kataklasm** [comment]
For anyone coming across this: I was initially searching for atlantis.vim again because I liked how it was more green compared to nord-vim. Since it's unfortunately abandoned now I decided to modify nord-vim to my liking and publish my changes as [forest-nord-vim](https://github.com/cramermarius/forest-nord-vim) on my profile. This is not supposed to be an ad for my profile nor my project, and if you feel like it it feel free to remove this comment, but only exists to help other people on their search for a more green nord-vim.
